import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

import { readArtifact } from "./artifacts.ts";
import { OUT_DIR } from "./paths.ts";

// Build artifacts the runtime reads at boot. Keep in sync with readArtifact() callers.
export const RUNTIME_ARTIFACTS = ["manifest.json", "app-html.json", "route-manifest.json"];

/**
 * Write `.bosia/artifacts.ts` — a filesystem-free drop-in for artifacts.ts with
 * every runtime artifact inlined. Call after the build has written them.
 */
export function generateArtifactsModule(outDir: string = OUT_DIR, cwd = process.cwd()): string {
	const files: Record<string, unknown> = {};
	for (const name of RUNTIME_ARTIFACTS) {
		const value = readArtifact(name, outDir);
		if (value !== undefined) files[name] = value;
	}
	const target = join(cwd, ".bosia", "artifacts.ts");
	mkdirSync(join(cwd, ".bosia"), { recursive: true });
	writeFileSync(
		target,
		"// Auto-generated by Bosia. Do not edit.\n" +
			`const files: Record<string, unknown> = ${JSON.stringify(files)};\n\n` +
			"export function readArtifact<T>(name: string, _dir?: string): T | undefined {\n" +
			"\treturn files[name] as T | undefined;\n" +
			"}\n",
	);
	return target;
}
