import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { basename, join } from "path";

import { readArtifact } from "./artifacts.ts";
import { findConfigPath } from "./config.ts";
import { OUT_DIR, toPosix } from "./paths.ts";

// ─── Workers Codegen ─────────────────────────────────────
// Cloudflare Workers has no filesystem and no dynamic `import(<path>)`, so
// everything the Bun server reads or imports off disk at boot is generated
// into `.bosia/` as static code the worker bundle can inline.

// Build artifacts the runtime reads at boot. Keep in sync with readArtifact() callers.
export const RUNTIME_ARTIFACTS = ["manifest.json", "app-html.json", "route-manifest.json"];

const HEADER = "// Auto-generated by Bosia. Do not edit.\n";

function writeBosiaFile(cwd: string, name: string, code: string): string {
	const target = join(cwd, ".bosia", name);
	mkdirSync(join(cwd, ".bosia"), { recursive: true });
	writeFileSync(target, HEADER + code);
	return target;
}

/**
 * Write `.bosia/artifacts.ts` — a filesystem-free drop-in for artifacts.ts with
 * every runtime artifact inlined. Call after the build has written them.
 */
export function generateArtifactsModule(outDir: string = OUT_DIR, cwd = process.cwd()): string {
	const files: Record<string, unknown> = {};
	for (const name of RUNTIME_ARTIFACTS) {
		const value = readArtifact(name, outDir);
		if (value !== undefined) files[name] = value;
	}
	return writeBosiaFile(
		cwd,
		"artifacts.ts",
		`const files: Record<string, unknown> = ${JSON.stringify(files)};\n\n` +
			"export function readArtifact<T>(name: string, _dir?: string): T | undefined {\n" +
			"\treturn files[name] as T | undefined;\n" +
			"}\n",
	);
}

/**
 * Write `.bosia/runtime.workers.ts` (`bosia:workers-runtime`) — static imports
 * of the app's `src/hooks.server.ts` and `bosia.config.*`, which the Bun server
 * loads with a dynamic `import()` of an absolute path.
 */
export function generateWorkersRuntime(cwd = process.cwd()): string {
	const hooksPath = join(cwd, "src", "hooks.server.ts");
	const configPath = findConfigPath(cwd);
	const lines: string[] = [];
	if (existsSync(hooksPath)) {
		lines.push(`import * as hooks from ${JSON.stringify(toPosix(hooksPath))};`);
		lines.push(`export const handle = typeof hooks.handle === "function" ? hooks.handle : null;`);
	} else {
		lines.push("export const handle = null;");
	}
	if (configPath) {
		lines.push(`export { default as config } from ${JSON.stringify(toPosix(configPath))};`);
	} else {
		lines.push("export const config = {};");
	}
	return writeBosiaFile(cwd, "runtime.workers.ts", lines.join("\n") + "\n");
}

/**
 * Write `wrangler.jsonc` at the app root, unless one exists — it's where the
 * user adds bindings (D1, KV, vars), so a rebuild must never overwrite it.
 * Returns the path when written, null when left alone.
 */
export function generateWranglerConfig(
	cwd = process.cwd(),
	outDir: string = OUT_DIR,
): string | null {
	const target = join(cwd, "wrangler.jsonc");
	if (
		existsSync(target) ||
		existsSync(join(cwd, "wrangler.json")) ||
		existsSync(join(cwd, "wrangler.toml"))
	)
		return null;
	let name = basename(cwd);
	try {
		name = JSON.parse(readFileSync(join(cwd, "package.json"), "utf-8")).name || name;
	} catch {}
	// Worker names: lowercase letters, digits and dashes. Drops an npm @scope/.
	name =
		name
			.replace(/^@[^/]+\//, "")
			.toLowerCase()
			.replace(/[^a-z0-9-]+/g, "-") || "bosia-app";
	const dir = toPosix(outDir).replace(/^\.\//, "");
	const config = {
		name,
		main: `./${dir}/worker/index.js`,
		compatibility_date: "2025-09-01",
		compatibility_flags: ["nodejs_compat"],
		// Served before the worker runs; misses fall through to it.
		assets: { directory: `./${dir}/static` },
	};
	writeFileSync(
		target,
		"// Generated once by `bosia build --target=workers`. Yours to edit — add bindings here.\n" +
			JSON.stringify(config, null, "\t") +
			"\n",
	);
	return target;
}
