import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { ClassifiedEnv } from "./env.ts";

// ─── Env Module Codegen ──────────────────────────────────
// Generates three files in .bosbun/:
//   env.server.ts  — all vars (static inlined, dynamic via process.env)
//   env.client.ts  — only PUBLIC_* vars (PUBLIC_STATIC_* inlined, PUBLIC_* via window.__BOSBUN_ENV__)
//   types/env.d.ts — declare module '$env' for IDE autocomplete

export function generateEnvModules(classified: ClassifiedEnv): void {
    const bosbunDir = join(process.cwd(), ".bosbun");
    const typesDir = join(bosbunDir, "types");
    mkdirSync(bosbunDir, { recursive: true });
    mkdirSync(typesDir, { recursive: true });

    writeServerEnv(classified, bosbunDir);
    writeClientEnv(classified, bosbunDir);
    writeEnvTypes(classified, typesDir);
}

function writeServerEnv(classified: ClassifiedEnv, bosbunDir: string): void {
    const lines: string[] = [
        "// Auto-generated by Bosbun. Do not edit.",
        "// $env → server — all vars",
        "",
    ];

    // PUBLIC_STATIC_* — inlined literals
    for (const [key, value] of Object.entries(classified.publicStatic)) {
        lines.push(`export const ${key} = ${JSON.stringify(value)};`);
    }

    // PUBLIC_* dynamic — read from process.env at runtime
    for (const key of Object.keys(classified.publicDynamic)) {
        lines.push(`export const ${key} = process.env.${key} ?? "";`);
    }

    // STATIC_* — inlined literals
    for (const [key, value] of Object.entries(classified.privateStatic)) {
        lines.push(`export const ${key} = ${JSON.stringify(value)};`);
    }

    // private dynamic — read from process.env at runtime
    for (const key of Object.keys(classified.privateDynamic)) {
        lines.push(`export const ${key} = process.env.${key} ?? "";`);
    }

    writeFileSync(join(bosbunDir, "env.server.ts"), lines.join("\n") + "\n");
}

function writeClientEnv(classified: ClassifiedEnv, bosbunDir: string): void {
    const lines: string[] = [
        "// Auto-generated by Bosbun. Do not edit.",
        "// $env → client — PUBLIC_* vars only",
        "",
        "const __env: Record<string, string> =",
        "  typeof window !== 'undefined' && (window as any).__BOSBUN_ENV__ || {};",
        "",
    ];

    // PUBLIC_STATIC_* — inlined literals
    for (const [key, value] of Object.entries(classified.publicStatic)) {
        lines.push(`export const ${key} = ${JSON.stringify(value)};`);
    }

    // PUBLIC_* dynamic — read from window.__BOSBUN_ENV__ at runtime
    for (const key of Object.keys(classified.publicDynamic)) {
        lines.push(`export const ${key} = __env.${key} ?? "";`);
    }

    writeFileSync(join(bosbunDir, "env.client.ts"), lines.join("\n") + "\n");
}

function writeEnvTypes(classified: ClassifiedEnv, typesDir: string): void {
    const allKeys = [
        ...Object.keys(classified.publicStatic),
        ...Object.keys(classified.publicDynamic),
        ...Object.keys(classified.privateStatic),
        ...Object.keys(classified.privateDynamic),
    ];

    const declarations = allKeys.map(key => `    export const ${key}: string;`);

    const content = [
        "// Auto-generated by Bosbun. Do not edit.",
        "declare module '$env' {",
        ...declarations,
        "}",
        "",
    ].join("\n");

    writeFileSync(join(typesDir, "env.d.ts"), content);
}
