// Per-purpose seed content, ported from Mercato's data.js. One storefront, many
// purposes: the same blocks render any of these — switch `purpose` to re-skin the
// copy and catalogue. Pair with a matching theme (see the bosia-storefront skill):
//   clay→clay · fashion→editorial · grocery→forest · tech→paper · beauty→bloom · garden→sage
import type { Product } from "./store.svelte.ts";

export interface Hero {
	eyebrow: string;
	title: string;
	sub: string;
	cta: string;
	cta2: string;
}

export interface Purpose {
	key: string;
	label: string;
	hero: Hero;
	categories: string[];
	nav: string[];
	products: Product[];
}

// A small shared image pool keeps the seed light; assign by index so every
// catalogue has imagery without hand-picking 48 photos.
const POOL = [
	"https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&q=80",
	"https://images.unsplash.com/photo-1600369671236-e74521d4b6ad?w=600&q=80",
	"https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
	"https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80",
	"https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&q=80",
	"https://images.unsplash.com/photo-1602874801006-e26c4c5b5b6a?w=600&q=80",
	"https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=600&q=80",
	"https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
];

type Seed = Omit<Product, "image"> & { i: number };
const build = (seeds: Seed[]): Product[] =>
	seeds.map(({ i, ...rest }) => ({ ...rest, image: POOL[i % POOL.length] }));

export const purposes: Record<string, Purpose> = {
	clay: {
		key: "clay",
		label: "General Store",
		hero: {
			eyebrow: "New season",
			title: "Good things for everyday living",
			sub: "A considered edit of homeware, pantry and lifestyle pieces — chosen to last, priced to love.",
			cta: "Shop the edit",
			cta2: "Our story",
		},
		categories: ["Home", "Kitchen", "Pantry", "Living", "Gifts"],
		nav: ["New In", "Home", "Kitchen", "Pantry", "Sale"],
		products: build([
			{
				i: 0,
				name: "Stoneware Dinner Set",
				category: "Kitchen",
				price: 78,
				badge: "new",
				rating: 4.8,
				reviews: 214,
				swatches: ["#C9B6A3", "#7C8A77", "#2A2419"],
			},
			{
				i: 1,
				name: "Linen Table Throw",
				category: "Living",
				price: 44,
				compareAt: 58,
				badge: "sale",
				rating: 4.6,
				reviews: 88,
			},
			{
				i: 2,
				name: "Cold-Press Olive Oil",
				category: "Pantry",
				price: 19,
				rating: 4.9,
				reviews: 312,
			},
			{
				i: 3,
				name: "Hand-Thrown Mug",
				category: "Kitchen",
				price: 24,
				rating: 4.7,
				reviews: 156,
				swatches: ["#E8D5C7", "#DCE6D5", "#E0E2E8"],
			},
			{ i: 4, name: "Wool Storage Basket", category: "Home", price: 52, rating: 4.5, reviews: 64 },
			{
				i: 5,
				name: "Beeswax Candle, Fig",
				category: "Living",
				price: 28,
				badge: "low",
				rating: 4.8,
				reviews: 203,
			},
			{
				i: 6,
				name: "Brass Serving Spoons",
				category: "Kitchen",
				price: 36,
				rating: 4.6,
				reviews: 41,
			},
			{
				i: 7,
				name: "Organic Sourdough Mix",
				category: "Pantry",
				price: 12,
				rating: 4.7,
				reviews: 122,
			},
		]),
	},
	fashion: {
		key: "fashion",
		label: "Fashion & Apparel",
		hero: {
			eyebrow: "Autumn / Winter",
			title: "Quiet luxury, made to be worn",
			sub: "Considered tailoring and elevated essentials in natural fibres. Designed in-studio, made in small runs.",
			cta: "Shop new arrivals",
			cta2: "The lookbook",
		},
		categories: ["Women", "Men", "Outerwear", "Knitwear", "Accessories"],
		nav: ["New In", "Women", "Men", "Outerwear", "Sale"],
		products: build([
			{
				i: 0,
				name: "Wool Overcoat",
				category: "Outerwear",
				price: 248,
				badge: "new",
				rating: 4.8,
				reviews: 96,
				swatches: ["#2A2419", "#7C7468", "#C9B6A3"],
			},
			{
				i: 1,
				name: "Merino Crew Knit",
				category: "Knitwear",
				price: 96,
				rating: 4.7,
				reviews: 142,
				swatches: ["#E7E1D6", "#2A2419", "#7C8A77"],
			},
			{
				i: 2,
				name: "Pleated Trouser",
				category: "Women",
				price: 128,
				compareAt: 165,
				badge: "sale",
				rating: 4.6,
				reviews: 73,
			},
			{ i: 3, name: "Oxford Shirt", category: "Men", price: 78, rating: 4.5, reviews: 211 },
			{ i: 4, name: "Leather Tote", category: "Accessories", price: 184, rating: 4.9, reviews: 89 },
			{
				i: 5,
				name: "Cashmere Scarf",
				category: "Accessories",
				price: 110,
				badge: "low",
				rating: 4.8,
				reviews: 54,
			},
			{ i: 6, name: "Tailored Blazer", category: "Women", price: 198, rating: 4.7, reviews: 38 },
			{
				i: 7,
				name: "Silk Slip Dress",
				category: "Women",
				price: 142,
				badge: "new",
				rating: 4.6,
				reviews: 61,
			},
		]),
	},
	grocery: {
		key: "grocery",
		label: "Grocery & Fresh",
		hero: {
			eyebrow: "Picked today",
			title: "Fresh from the market, to your door",
			sub: "Seasonal produce, local dairy and pantry staples — sourced from growers we know by name.",
			cta: "Start your basket",
			cta2: "Meet our growers",
		},
		categories: ["Produce", "Bakery", "Dairy", "Pantry", "Drinks"],
		nav: ["Weekly Box", "Produce", "Bakery", "Dairy", "Offers"],
		products: build([
			{
				i: 0,
				name: "Heirloom Tomatoes, 500g",
				category: "Produce",
				price: 6,
				badge: "new",
				rating: 4.8,
				reviews: 128,
			},
			{ i: 1, name: "Sourdough Boule", category: "Bakery", price: 5, rating: 4.9, reviews: 421 },
			{ i: 2, name: "Free-Range Eggs, 6", category: "Dairy", price: 4, rating: 4.7, reviews: 96 },
			{
				i: 3,
				name: "Cold-Brew Coffee, 1L",
				category: "Drinks",
				price: 8,
				compareAt: 10,
				badge: "sale",
				rating: 4.6,
				reviews: 152,
			},
			{
				i: 4,
				name: "Rainbow Chard Bunch",
				category: "Produce",
				price: 3,
				rating: 4.5,
				reviews: 33,
			},
			{
				i: 5,
				name: "Raw Wildflower Honey",
				category: "Pantry",
				price: 11,
				badge: "low",
				rating: 4.8,
				reviews: 174,
			},
			{ i: 6, name: "Buffalo Mozzarella", category: "Dairy", price: 7, rating: 4.6, reviews: 88 },
			{
				i: 7,
				name: "Stone Fruit Box",
				category: "Produce",
				price: 14,
				badge: "new",
				rating: 4.7,
				reviews: 64,
			},
		]),
	},
	tech: {
		key: "tech",
		label: "Electronics & Tech",
		hero: {
			eyebrow: "Just launched",
			title: "Tools that keep up with you",
			sub: "Audio, desk and everyday carry — tested for the way you actually work. Two-year warranty, always.",
			cta: "Shop new tech",
			cta2: "Compare models",
		},
		categories: ["Audio", "Desk", "Mobile", "Power", "Smart Home"],
		nav: ["New", "Audio", "Desk", "Power", "Deals"],
		products: build([
			{
				i: 0,
				name: "Studio Headphones",
				category: "Audio",
				price: 199,
				badge: "new",
				rating: 4.8,
				reviews: 188,
				swatches: ["#2A2419", "#E0E2E8", "#DDE2F5"],
			},
			{
				i: 1,
				name: "Mechanical Keyboard",
				category: "Desk",
				price: 129,
				rating: 4.8,
				reviews: 256,
			},
			{
				i: 2,
				name: "USB-C Power Bank 20K",
				category: "Power",
				price: 49,
				compareAt: 65,
				badge: "sale",
				rating: 4.6,
				reviews: 142,
			},
			{
				i: 3,
				name: "Wireless Earbuds Pro",
				category: "Audio",
				price: 159,
				rating: 4.7,
				reviews: 203,
			},
			{ i: 4, name: "4K Webcam", category: "Desk", price: 89, rating: 4.5, reviews: 76 },
			{
				i: 5,
				name: "Smart Desk Lamp",
				category: "Desk",
				price: 72,
				badge: "low",
				rating: 4.8,
				reviews: 51,
			},
			{
				i: 6,
				name: "Charging Dock 3-in-1",
				category: "Power",
				price: 79,
				rating: 4.6,
				reviews: 64,
			},
			{
				i: 7,
				name: "Bluetooth Speaker",
				category: "Audio",
				price: 119,
				badge: "new",
				rating: 4.7,
				reviews: 98,
			},
		]),
	},
	beauty: {
		key: "beauty",
		label: "Beauty & Skincare",
		hero: {
			eyebrow: "Clean ritual",
			title: "Skin-first beauty, beautifully simple",
			sub: "Gentle, effective formulas with ingredients you can pronounce. Dermatologist-tested, never on animals.",
			cta: "Build your routine",
			cta2: "Take the skin quiz",
		},
		categories: ["Skincare", "Serums", "Body", "Makeup", "Sets"],
		nav: ["New", "Skincare", "Serums", "Body", "Bestsellers"],
		products: build([
			{
				i: 0,
				name: "Hydrating Serum",
				category: "Serums",
				price: 38,
				badge: "new",
				rating: 4.9,
				reviews: 512,
			},
			{
				i: 1,
				name: "Gentle Gel Cleanser",
				category: "Skincare",
				price: 24,
				rating: 4.7,
				reviews: 188,
			},
			{
				i: 2,
				name: "Vitamin C Drops",
				category: "Serums",
				price: 42,
				compareAt: 52,
				badge: "sale",
				rating: 4.6,
				reviews: 142,
			},
			{
				i: 3,
				name: "Silk Lip Balm",
				category: "Makeup",
				price: 16,
				rating: 4.8,
				reviews: 96,
				swatches: ["#C24E7D", "#B5512F", "#7C5C6A"],
			},
			{
				i: 4,
				name: "Restoring Night Cream",
				category: "Skincare",
				price: 48,
				badge: "low",
				rating: 4.7,
				reviews: 74,
			},
			{ i: 5, name: "Body Butter, Neroli", category: "Body", price: 28, rating: 4.6, reviews: 63 },
			{ i: 6, name: "Mineral SPF 40", category: "Skincare", price: 32, rating: 4.8, reviews: 211 },
			{
				i: 7,
				name: "The Starter Set",
				category: "Sets",
				price: 64,
				badge: "new",
				rating: 4.9,
				reviews: 128,
			},
		]),
	},
	garden: {
		key: "garden",
		label: "Plants & Garden",
		hero: {
			eyebrow: "Grow season",
			title: "For people who garden, indoors & out",
			sub: "Houseplants, tools and seed — with the know-how to keep everything thriving. Delivered with care.",
			cta: "Shop the greenhouse",
			cta2: "Plant care guides",
		},
		categories: ["Houseplants", "Pots", "Tools", "Seeds", "Care"],
		nav: ["New", "Houseplants", "Pots", "Tools", "Sale"],
		products: build([
			{
				i: 0,
				name: "Fiddle-Leaf Fig",
				category: "Houseplants",
				price: 58,
				badge: "new",
				rating: 4.7,
				reviews: 96,
			},
			{ i: 1, name: "Terracotta Pot Set", category: "Pots", price: 34, rating: 4.6, reviews: 142 },
			{
				i: 2,
				name: "Brass Watering Can",
				category: "Tools",
				price: 46,
				compareAt: 60,
				badge: "sale",
				rating: 4.8,
				reviews: 73,
			},
			{
				i: 3,
				name: "Heirloom Seed Library",
				category: "Seeds",
				price: 22,
				rating: 4.7,
				reviews: 64,
			},
			{
				i: 4,
				name: "Monstera Deliciosa",
				category: "Houseplants",
				price: 42,
				rating: 4.6,
				reviews: 88,
			},
			{
				i: 5,
				name: "Pruning Shears",
				category: "Tools",
				price: 28,
				badge: "low",
				rating: 4.8,
				reviews: 51,
			},
			{ i: 6, name: "Organic Potting Mix", category: "Care", price: 14, rating: 4.5, reviews: 33 },
			{
				i: 7,
				name: "Trailing Pothos",
				category: "Houseplants",
				price: 26,
				badge: "new",
				rating: 4.7,
				reviews: 47,
			},
		]),
	},
};

export const purposeOrder = ["clay", "fashion", "grocery", "tech", "beauty", "garden"];
