import { writeFileSync, mkdirSync } from "fs";
import type { RouteManifest } from "./types.ts";

// ─── Route File Generator ─────────────────────────────────
// Generates .bunia/routes.ts — ONE file with three exports:
//   clientRoutes  — used by client hydrator (page + layout lazy imports)
//   serverRoutes  — used by SSR renderer (+ pageServer + layoutServers)
//   apiRoutes     — used by API handler

export function generateRoutesFile(manifest: RouteManifest): void {
    const lines: string[] = [
        "// AUTO-GENERATED by bunia build — do not edit\n",
    ];

    // clientRoutes
    lines.push("export const clientRoutes: Array<{");
    lines.push("  pattern: string;");
    lines.push("  page: () => Promise<any>;");
    lines.push("  layouts: (() => Promise<any>)[];");
    lines.push("  hasServerData: boolean;");
    lines.push("}> = [");
    for (const r of manifest.pages) {
        const layoutImports = r.layouts
            .map(l => `() => import(${JSON.stringify(toImportPath(l))})`)
            .join(", ");
        const hasServerData = !!(r.pageServer || r.layoutServers.length > 0);
        lines.push("  {");
        lines.push(`    pattern: ${JSON.stringify(r.pattern)},`);
        lines.push(`    page: () => import(${JSON.stringify(toImportPath(r.page))}),`);
        lines.push(`    layouts: [${layoutImports}],`);
        lines.push(`    hasServerData: ${hasServerData},`);
        lines.push("  },");
    }
    lines.push("];\n");

    // serverRoutes
    lines.push("export const serverRoutes: Array<{");
    lines.push("  pattern: string;");
    lines.push("  pageModule: () => Promise<any>;");
    lines.push("  layoutModules: (() => Promise<any>)[];");
    lines.push("  pageServer: (() => Promise<any>) | null;");
    lines.push("  layoutServers: { loader: () => Promise<any>; depth: number }[];");
    lines.push("}> = [");
    for (const r of manifest.pages) {
        const layoutImports = r.layouts
            .map(l => `() => import(${JSON.stringify(toImportPath(l))})`)
            .join(", ");
        const layoutServerImports = r.layoutServers
            .map(ls => `{ loader: () => import(${JSON.stringify(toImportPath(ls.path))}), depth: ${ls.depth} }`)
            .join(", ");
        lines.push("  {");
        lines.push(`    pattern: ${JSON.stringify(r.pattern)},`);
        lines.push(`    pageModule: () => import(${JSON.stringify(toImportPath(r.page))}),`);
        lines.push(`    layoutModules: [${layoutImports}],`);
        lines.push(`    pageServer: ${r.pageServer ? `() => import(${JSON.stringify(toImportPath(r.pageServer))})` : "null"},`);
        lines.push(`    layoutServers: [${layoutServerImports}],`);
        lines.push("  },");
    }
    lines.push("];\n");

    // apiRoutes
    lines.push("export const apiRoutes: Array<{");
    lines.push("  pattern: string;");
    lines.push("  module: () => Promise<any>;");
    lines.push("}> = [");
    for (const r of manifest.apis) {
        lines.push("  {");
        lines.push(`    pattern: ${JSON.stringify(r.pattern)},`);
        lines.push(`    module: () => import(${JSON.stringify(toImportPath(r.server))}),`);
        lines.push("  },");
    }
    lines.push("];\n");

    // errorPage
    const ep = manifest.errorPage;
    lines.push(`export const errorPage: (() => Promise<any>) | null = ${
        ep ? `() => import(${JSON.stringify(toImportPath(ep))})` : "null"
    };\n`);

    mkdirSync(".bunia", { recursive: true });
    writeFileSync(".bunia/routes.ts", lines.join("\n"));
    console.log("✅ Routes generated: .bunia/routes.ts");
}

// Import path from .bunia/routes.ts to src/routes/<routePath>
function toImportPath(routePath: string): string {
    return "../src/routes/" + routePath.replace(/\\/g, "/");
}
